version: "3.8"

services:
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    ports:
      - "9335:9333" # Master (port lokal 9335)
      - "8082:8080" # Volume (port lokal 8082)
      - "8890:8888" # Filer (port lokal 8890)
      - "8335:8333" # S3 API (port lokal 8335)
    command: "server -s3 -dir=/data"
    volumes:
      - seaweed_data:/data
    environment:
      - WEED_MASTER_VOLUME_SIZE_LIMIT_MB=1024

  postgres:
    image: postgres:15-alpine
    ports:
      - "5434:5432" # Port lokal 5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  seaweed_data:
  postgres_data:
